nelmio_api_doc:
    documentation:
        openapi: 3.0.0
        info:
            title: POC API
            description: Documentation OpenAPI de l'API POC (Symfony 7)
            version: 1.0.0
        servers:
            - url: http://localhost
              description: Local
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc)