controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# NelmioApiDoc - OpenAPI JSON
nelmio_api_doc:
    path: /api/doc.json
    controller: nelmio_api_doc.controller.swagger
    methods: [GET]

# NelmioApiDoc - Swagger UI
nelmio_api_doc_ui:
    path: /api/doc
    controller: nelmio_api_doc.controller.swagger_ui
    methods: [GET]